add producedAnalyses to query; add logic to filter suppressed producedAnalyses
icgc-argo/donor-submission-aggregator pull request #134
Opened 2021-01-26 21:41 UTC by Buwujiu

2021-01-27 15:46 UTC, joneubank requested changes

2021-01-27 15:46 UTC, joneubank commented on src/rdpc/analysesProcessor.ts
> +    const filteredRuns = analysis.runs.reduce<Run[]>((_acc, run) => {
Don't be afraid to use longer names to make the different accumulators more readable. Maybe:
`resultAcc` and `runsAcc`

2021-01-27 15:46 UTC, joneubank commented on src/rdpc/fetchAnalyses.ts
> +            (filter: { analysisState: PUBLISHED}) {
👍

2021-01-27 15:46 UTC, joneubank commented on src/rdpc/analysesProcessor.ts
> +    analysis.runs = filteredRuns;
We shouldn't be modifying the query contents like this. Consider making a new object with the data we want to pass on and adding that to your result.

2021-01-27 15:46 UTC, joneubank commented on src/rdpc/analysesProcessor.ts
> +    const filteredRuns = analysis.runs.reduce<Run[]>((_acc, run) => {
This just looks like a filter operation, can you simplify this block?
```
const filteredRuns = analysis.runs.filter(run => run.producedAnalyses && run.producedAnalyses.length > 0);
```

2021-01-27 16:45 UTC, joneubank approved these changes
Thanks for the updates! Good stuff here.

2021-01-27 16:45 UTC, merged

2021-02-03 15:59 UTC, Buwujiu commented
version = 1.16.1